python 3.6 warning: pathlib.Path.resolve() works differently in 3.6
resolving file name to current directory.
So variable_name_endings_to_normpath create wrong paths and should be replaced.
